import type {
  Customer,
  Quote,
  Booking,
  Truck,
  Expense,
  DashboardStats,
  Note,
  Invoice,
  AppNotification,
  MaintenanceRecord,
  FuelLog,
} from '@/types';

// ============================================
// Helper: get dates relative to today
// ============================================

function today() {
  return new Date();
}

function dateOffset(days: number): string {
  const d = today();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

function isoOffset(days: number): string {
  const d = today();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

// ============================================
// Customers
// ============================================

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    name: 'Carlos Hernandez',
    phone: '+13055551001',
    email: 'carlos.h@email.com',
    address: '1420 NW 7th Ave, Miami, FL 33136',
    company_name: 'Hernandez Remodeling LLC',
    customer_type: 'commercial',
    tags: ['contractor', 'recurring', 'vip'],
    internal_notes: [{ id: 'n-001', content: 'Excellent client — always pays on time. VIP pricing approved.', created_at: '2025-08-01T10:00:00Z', author: 'Admin' }],
    internal_rating: 5,
    credit_terms: 'net_15',
    preferred_payment: 'zelle',
    job_site_addresses: ['1420 NW 7th Ave, Miami, FL 33136', '2500 NW 79th Ave, Doral, FL 33122'],
    preferred_language: 'es',
    created_at: '2025-06-15T10:00:00Z',
    total_jobs: 24,
    total_revenue: 14280,
  },
  {
    id: 'cust-002',
    name: 'Maria Rodriguez',
    phone: '+13055551002',
    email: 'maria.r@email.com',
    address: '8901 SW 142nd Ave, Miami, FL 33186',
    customer_type: 'residential',
    tags: ['homeowner', 'one_time'],
    internal_notes: [],
    credit_terms: 'cod',
    job_site_addresses: [],
    preferred_language: 'es',
    created_at: '2025-11-20T14:00:00Z',
    total_jobs: 1,
    total_revenue: 350,
  },
  {
    id: 'cust-003',
    name: 'James Mitchell',
    phone: '+13055551003',
    email: 'james.m@buildersinc.com',
    address: '2200 Brickell Ave, Miami, FL 33129',
    company_name: 'Mitchell Builders Inc.',
    customer_type: 'commercial',
    tags: ['contractor', 'recurring'],
    internal_notes: [{ id: 'n-002', content: 'Large commercial projects. Usually needs full truck loads.', created_at: '2025-05-15T09:00:00Z', author: 'Admin' }],
    internal_rating: 4,
    credit_terms: 'net_30',
    preferred_payment: 'check',
    job_site_addresses: ['2200 Brickell Ave, Miami, FL 33129'],
    preferred_language: 'en',
    created_at: '2025-04-10T09:00:00Z',
    total_jobs: 18,
    total_revenue: 11400,
  },
  {
    id: 'cust-004',
    name: 'Ana Gutierrez',
    phone: '+13055551004',
    email: 'ana.g@email.com',
    address: '15600 SW 88th St, Miami, FL 33196',
    customer_type: 'residential',
    tags: ['homeowner'],
    internal_notes: [],
    credit_terms: 'cod',
    preferred_payment: 'cash',
    job_site_addresses: [],
    preferred_language: 'es',
    created_at: '2026-01-05T11:00:00Z',
    total_jobs: 3,
    total_revenue: 1050,
  },
  {
    id: 'cust-005',
    name: 'Robert Chen',
    phone: '+13055551005',
    email: 'robert.c@email.com',
    address: '7700 N Kendall Dr, Miami, FL 33156',
    company_name: 'Chen Property Group',
    customer_type: 'commercial',
    tags: ['contractor', 'vip'],
    internal_notes: [{ id: 'n-003', content: 'Property management company — multiple sites in Brickell and Kendall.', created_at: '2025-09-10T08:00:00Z', author: 'Admin' }],
    internal_rating: 5,
    credit_terms: 'net_15',
    preferred_payment: 'wire',
    job_site_addresses: ['7700 N Kendall Dr, Miami, FL 33156', '1200 Brickell Bay Dr, Miami, FL 33131'],
    preferred_language: 'en',
    created_at: '2025-08-22T08:00:00Z',
    total_jobs: 12,
    total_revenue: 8750,
  },
  {
    id: 'cust-006',
    name: 'Luis Perez',
    phone: '+13055551006',
    email: 'luis.p@perezroof.com',
    address: '3400 NW 36th St, Miami, FL 33142',
    company_name: 'Perez Roofing Co.',
    customer_type: 'commercial',
    tags: ['contractor', 'recurring'],
    internal_notes: [{ id: 'n-004', content: 'Roofing shingles only. Weekly pickups during active season.', created_at: '2025-10-01T10:00:00Z', author: 'Admin' }],
    internal_rating: 4,
    credit_terms: 'net_15',
    preferred_payment: 'zelle',
    job_site_addresses: ['3400 NW 36th St, Miami, FL 33142', '4100 NW 27th Ave, Miami, FL 33142'],
    preferred_language: 'es',
    created_at: '2025-09-01T10:00:00Z',
    total_jobs: 15,
    total_revenue: 9600,
  },
  {
    id: 'cust-007',
    name: 'Sarah Williams',
    phone: '+13055551007',
    email: 'sarah.w@email.com',
    address: '1100 S Miami Ave, Miami, FL 33130',
    customer_type: 'residential',
    tags: ['homeowner', 'one_time'],
    internal_notes: [],
    credit_terms: 'cod',
    job_site_addresses: [],
    preferred_language: 'en',
    created_at: '2026-02-14T16:00:00Z',
    total_jobs: 1,
    total_revenue: 280,
  },
  {
    id: 'cust-008',
    name: 'Fernando Diaz',
    phone: '+13055551008',
    email: 'fernando.d@diazdemolition.com',
    address: '5500 NW 72nd Ave, Miami, FL 33166',
    company_name: 'Diaz Demolition Services',
    customer_type: 'commercial',
    tags: ['contractor', 'recurring', 'vip'],
    internal_notes: [{ id: 'n-005', content: 'Highest-volume client. Retainer pricing approved. Always ask for Fernando at front office.', created_at: '2025-04-01T07:00:00Z', author: 'Admin' }],
    internal_rating: 5,
    credit_terms: 'net_30',
    preferred_payment: 'check',
    job_site_addresses: ['5500 NW 72nd Ave, Miami, FL 33166', '2800 NW 74th Ave, Miami, FL 33122'],
    preferred_language: 'es',
    created_at: '2025-03-10T07:00:00Z',
    total_jobs: 32,
    total_revenue: 22100,
  },
  {
    id: 'cust-009',
    name: 'Jennifer Adams',
    phone: '+13055551009',
    email: 'jennifer.a@email.com',
    address: '9200 SW 72nd St, Miami, FL 33173',
    customer_type: 'residential',
    tags: ['homeowner'],
    internal_notes: [],
    credit_terms: 'cod',
    preferred_payment: 'card',
    job_site_addresses: [],
    preferred_language: 'en',
    created_at: '2026-01-20T13:00:00Z',
    total_jobs: 2,
    total_revenue: 520,
  },
  {
    id: 'cust-010',
    name: 'Rafael Castillo',
    phone: '+13055551010',
    email: 'rafael.c@castillogroup.com',
    address: '6800 SW 40th St, Miami, FL 33155',
    company_name: 'Castillo General Contracting',
    customer_type: 'commercial',
    tags: ['contractor', 'recurring'],
    internal_notes: [],
    internal_rating: 3,
    credit_terms: 'net_15',
    preferred_payment: 'zelle',
    job_site_addresses: ['6800 SW 40th St, Miami, FL 33155'],
    preferred_language: 'es',
    created_at: '2025-07-18T09:00:00Z',
    total_jobs: 9,
    total_revenue: 6200,
  },
];

// ============================================
// Trucks
// ============================================

export const MOCK_TRUCKS: Truck[] = [
  {
    id: 'truck-001',
    name: 'Flash 1',
    plate_number: 'FL-NPR-14',
    capacity_tons: 12,
    status: 'available',
    mileage: 85200,
    maintenance_due: dateOffset(12),
    notes: '2014 Isuzu NPR — 12 cubic yard capacity',
    created_at: '2020-03-15T00:00:00Z',
  },
  {
    id: 'truck-002',
    name: 'Flash 2',
    plate_number: 'FL-NPR-06',
    capacity_tons: 12,
    status: 'in_use',
    mileage: 142100,
    maintenance_due: dateOffset(5),
    notes: '2006 Isuzu NPR — 12 cubic yard capacity',
    created_at: '2020-03-15T00:00:00Z',
  },
];

// ============================================
// Quotes
// ============================================

function quoteRef(n: number): string {
  return `FD-2026-${String(n).padStart(3, '0')}`;
}

export const MOCK_QUOTES: Quote[] = [
  {
    id: 'quote-001',
    reference: quoteRef(1),
    activity_log: [{ id: 'al-001', content: 'Quote created', created_at: isoOffset(-3), author: 'System' }, { id: 'al-002', content: 'Quote accepted by customer', created_at: isoOffset(-1), author: 'System' }],
    customer_id: 'cust-001',
    customer_name: 'Carlos Hernandez',
    customer_email: 'carlos.h@email.com',
    customer_phone: '+13055551001',
    waste_types: ['concrete_brick', 'metal_rebar'],
    load_size: 'heavy',
    address: '1420 NW 7th Ave, Miami, FL 33136',
    frequency: 'weekly',
    preferred_date: dateOffset(2),
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 298,
    estimated_price_max: 425,
    distance_miles: 8,
    status: 'accepted',
    created_at: isoOffset(-3),
    updated_at: isoOffset(-1),
  },
  {
    id: 'quote-002',
    reference: quoteRef(2),
    activity_log: [{ id: 'al-003', content: 'Quote created', created_at: isoOffset(-1), author: 'System' }],
    customer_id: 'cust-002',
    customer_name: 'Maria Rodriguez',
    customer_email: 'maria.r@email.com',
    customer_phone: '+13055551002',
    waste_types: ['mixed_debris'],
    load_size: 'light',
    address: '8901 SW 142nd Ave, Miami, FL 33186',
    frequency: 'one_time',
    preferred_date: dateOffset(4),
    time_slot: 'afternoon',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 200,
    estimated_price_max: 250,
    distance_miles: 18,
    status: 'new',
    created_at: isoOffset(-1),
    updated_at: isoOffset(-1),
  },
  {
    id: 'quote-003',
    reference: quoteRef(3),
    activity_log: [{ id: 'al-004', content: 'Quote created', created_at: isoOffset(-5), author: 'System' }, { id: 'al-005', content: 'Quote sent to customer', created_at: isoOffset(-2), author: 'Admin' }],
    customer_id: 'cust-003',
    customer_name: 'James Mitchell',
    customer_email: 'james.m@buildersinc.com',
    customer_phone: '+13055551003',
    waste_types: ['drywall_plaster', 'wood_lumber'],
    load_size: 'medium',
    address: '2200 Brickell Ave, Miami, FL 33129',
    frequency: 'biweekly',
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 225,
    estimated_price_max: 315,
    distance_miles: 5,
    status: 'sent',
    created_at: isoOffset(-5),
    updated_at: isoOffset(-2),
  },
  {
    id: 'quote-004',
    reference: quoteRef(4),
    activity_log: [{ id: 'al-006', content: 'Quote created', created_at: isoOffset(0), author: 'System' }],
    customer_id: 'cust-004',
    customer_name: 'Ana Gutierrez',
    customer_email: 'ana.g@email.com',
    customer_phone: '+13055551004',
    waste_types: ['tile_ceramic'],
    load_size: 'light',
    address: '15600 SW 88th St, Miami, FL 33196',
    frequency: 'one_time',
    preferred_date: dateOffset(1),
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 200,
    estimated_price_max: 250,
    distance_miles: 22,
    status: 'new',
    created_at: isoOffset(0),
    updated_at: isoOffset(0),
  },
  {
    id: 'quote-005',
    reference: quoteRef(5),
    activity_log: [{ id: 'al-007', content: 'Quote created', created_at: isoOffset(-2), author: 'System' }, { id: 'al-008', content: 'Quote reviewed', created_at: isoOffset(-1), author: 'Admin' }],
    customer_id: 'cust-005',
    customer_name: 'Robert Chen',
    customer_email: 'robert.c@email.com',
    customer_phone: '+13055551005',
    waste_types: ['appliances_fixtures', 'mixed_debris'],
    load_size: 'medium',
    address: '7700 N Kendall Dr, Miami, FL 33156',
    frequency: 'one_time',
    preferred_date: dateOffset(3),
    time_slot: 'afternoon',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 250,
    estimated_price_max: 350,
    distance_miles: 12,
    status: 'reviewed',
    created_at: isoOffset(-2),
    updated_at: isoOffset(-1),
  },
  {
    id: 'quote-006',
    reference: quoteRef(6),
    activity_log: [{ id: 'al-009', content: 'Quote created', created_at: isoOffset(-7), author: 'System' }, { id: 'al-010', content: 'Quote accepted', created_at: isoOffset(-4), author: 'System' }],
    customer_id: 'cust-006',
    customer_name: 'Luis Perez',
    customer_email: 'luis.p@perezroof.com',
    customer_phone: '+13055551006',
    waste_types: ['roofing_shingles'],
    load_size: 'full_truck',
    address: '3400 NW 36th St, Miami, FL 33142',
    frequency: 'weekly',
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 425,
    estimated_price_max: 553,
    distance_miles: 6,
    status: 'accepted',
    created_at: isoOffset(-7),
    updated_at: isoOffset(-4),
  },
  {
    id: 'quote-007',
    reference: quoteRef(7),
    activity_log: [{ id: 'al-011', content: 'Quote created', created_at: isoOffset(-4), author: 'System' }, { id: 'al-012', content: 'Quote sent', created_at: isoOffset(-3), author: 'Admin' }],
    customer_id: 'cust-007',
    customer_name: 'Sarah Williams',
    customer_email: 'sarah.w@email.com',
    customer_phone: '+13055551007',
    waste_types: ['wood_lumber'],
    load_size: 'light',
    address: '1100 S Miami Ave, Miami, FL 33130',
    frequency: 'one_time',
    preferred_date: dateOffset(5),
    time_slot: 'afternoon',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 200,
    estimated_price_max: 250,
    distance_miles: 4,
    status: 'sent',
    created_at: isoOffset(-4),
    updated_at: isoOffset(-3),
  },
  {
    id: 'quote-008',
    reference: quoteRef(8),
    activity_log: [{ id: 'al-013', content: 'Quote created', created_at: isoOffset(-10), author: 'System' }, { id: 'al-014', content: 'Converted to booking', created_at: isoOffset(-6), author: 'Admin' }],
    customer_id: 'cust-008',
    customer_name: 'Fernando Diaz',
    customer_email: 'fernando.d@diazdemolition.com',
    customer_phone: '+13055551008',
    waste_types: ['concrete_brick', 'metal_rebar', 'mixed_debris'],
    load_size: 'full_truck',
    address: '5500 NW 72nd Ave, Miami, FL 33166',
    frequency: 'retainer',
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 400,
    estimated_price_max: 520,
    distance_miles: 10,
    status: 'booked',
    created_at: isoOffset(-10),
    updated_at: isoOffset(-6),
  },
  {
    id: 'quote-009',
    reference: quoteRef(9),
    activity_log: [{ id: 'al-015', content: 'Quote created', created_at: isoOffset(-20), author: 'System' }, { id: 'al-016', content: 'Quote expired', created_at: isoOffset(-14), author: 'System' }],
    customer_id: 'cust-009',
    customer_name: 'Jennifer Adams',
    customer_email: 'jennifer.a@email.com',
    customer_phone: '+13055551009',
    waste_types: ['drywall_plaster'],
    load_size: 'light',
    address: '9200 SW 72nd St, Miami, FL 33173',
    frequency: 'one_time',
    preferred_date: dateOffset(6),
    time_slot: 'afternoon',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 200,
    estimated_price_max: 250,
    distance_miles: 14,
    status: 'expired',
    created_at: isoOffset(-20),
    updated_at: isoOffset(-14),
  },
  {
    id: 'quote-010',
    reference: quoteRef(10),
    activity_log: [{ id: 'al-017', content: 'Quote created', created_at: isoOffset(-3), author: 'System' }],
    customer_id: 'cust-010',
    customer_name: 'Rafael Castillo',
    customer_email: 'rafael.c@castillogroup.com',
    customer_phone: '+13055551010',
    waste_types: ['wood_lumber', 'drywall_plaster'],
    load_size: 'heavy',
    address: '6800 SW 40th St, Miami, FL 33155',
    frequency: 'biweekly',
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 315,
    estimated_price_max: 450,
    distance_miles: 9,
    status: 'priced',
    created_at: isoOffset(-3),
    updated_at: isoOffset(-1),
  },
  {
    id: 'quote-011',
    reference: quoteRef(11),
    activity_log: [{ id: 'al-018', content: 'Emergency quote created', created_at: isoOffset(0), author: 'System' }],
    customer_name: 'David Lopez',
    customer_email: 'david.l@email.com',
    customer_phone: '+13055551011',
    waste_types: ['mixed_debris'],
    load_size: 'medium',
    address: '12000 SW 8th St, Miami, FL 33184',
    frequency: 'one_time',
    preferred_date: dateOffset(2),
    time_slot: 'morning',
    is_emergency: true,
    photo_urls: [],
    estimated_price_min: 250,
    estimated_price_max: 350,
    distance_miles: 16,
    status: 'new',
    created_at: isoOffset(0),
    updated_at: isoOffset(0),
  },
  {
    id: 'quote-012',
    reference: quoteRef(12),
    activity_log: [{ id: 'al-019', content: 'Quote created', created_at: isoOffset(-1), author: 'System' }, { id: 'al-020', content: 'Quote reviewed', created_at: isoOffset(0), author: 'Admin' }],
    customer_id: 'cust-001',
    customer_name: 'Carlos Hernandez',
    customer_email: 'carlos.h@email.com',
    customer_phone: '+13055551001',
    waste_types: ['concrete_brick'],
    load_size: 'medium',
    address: '2500 NW 79th Ave, Doral, FL 33122',
    frequency: 'weekly',
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 213,
    estimated_price_max: 298,
    distance_miles: 11,
    status: 'reviewed',
    created_at: isoOffset(-1),
    updated_at: isoOffset(0),
  },
  {
    id: 'quote-013',
    reference: quoteRef(13),
    activity_log: [{ id: 'al-021', content: 'Quote created', created_at: isoOffset(-6), author: 'System' }, { id: 'al-022', content: 'Quote sent', created_at: isoOffset(-4), author: 'Admin' }],
    customer_id: 'cust-005',
    customer_name: 'Robert Chen',
    customer_email: 'robert.c@email.com',
    customer_phone: '+13055551005',
    waste_types: ['tile_ceramic', 'appliances_fixtures'],
    load_size: 'heavy',
    address: '7700 N Kendall Dr, Miami, FL 33156',
    frequency: 'one_time',
    time_slot: 'afternoon',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 350,
    estimated_price_max: 500,
    distance_miles: 12,
    status: 'sent',
    created_at: isoOffset(-6),
    updated_at: isoOffset(-4),
  },
  {
    id: 'quote-014',
    reference: quoteRef(14),
    activity_log: [{ id: 'al-023', content: 'Quote created', created_at: isoOffset(0), author: 'System' }],
    customer_id: 'cust-006',
    customer_name: 'Luis Perez',
    customer_email: 'luis.p@perezroof.com',
    customer_phone: '+13055551006',
    waste_types: ['roofing_shingles', 'wood_lumber'],
    load_size: 'heavy',
    address: '4100 NW 27th Ave, Miami, FL 33142',
    frequency: 'weekly',
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 298,
    estimated_price_max: 425,
    distance_miles: 7,
    status: 'new',
    created_at: isoOffset(0),
    updated_at: isoOffset(0),
  },
  {
    id: 'quote-015',
    reference: quoteRef(15),
    activity_log: [{ id: 'al-024', content: 'Quote created', created_at: isoOffset(0), author: 'System' }],
    customer_name: 'Patricia Morales',
    customer_email: 'patricia.m@email.com',
    customer_phone: '+13055551015',
    waste_types: ['mixed_debris'],
    load_size: 'light',
    address: '18200 SW 127th Ave, Miami, FL 33177',
    frequency: 'one_time',
    preferred_date: dateOffset(7),
    time_slot: 'afternoon',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 200,
    estimated_price_max: 250,
    distance_miles: 25,
    status: 'new',
    created_at: isoOffset(0),
    updated_at: isoOffset(0),
  },
  {
    id: 'quote-016',
    reference: quoteRef(16),
    activity_log: [{ id: 'al-025', content: 'Quote created', created_at: isoOffset(-8), author: 'System' }, { id: 'al-026', content: 'Quote accepted', created_at: isoOffset(-5), author: 'System' }],
    customer_id: 'cust-008',
    customer_name: 'Fernando Diaz',
    customer_email: 'fernando.d@diazdemolition.com',
    customer_phone: '+13055551008',
    waste_types: ['concrete_brick', 'tile_ceramic'],
    load_size: 'full_truck',
    address: '2800 NW 74th Ave, Miami, FL 33122',
    frequency: 'retainer',
    time_slot: 'morning',
    is_emergency: false,
    photo_urls: [],
    estimated_price_min: 400,
    estimated_price_max: 520,
    distance_miles: 10,
    status: 'accepted',
    created_at: isoOffset(-8),
    updated_at: isoOffset(-5),
  },
];

// ============================================
// Bookings (across the current week)
// ============================================

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'book-001',
    quote_id: 'quote-001',
    customer_id: 'cust-001',
    truck_id: 'truck-001',
    scheduled_date: dateOffset(0),
    time_slot: 'morning',
    status: 'confirmed',
    address: '1420 NW 7th Ave, Miami, FL 33136',
    waste_types: ['concrete_brick', 'metal_rebar'],
    load_size: 'heavy',
    estimated_price: 425,
    special_instructions: 'Gate code: 4521',
    completion_photos: [],
    created_at: isoOffset(-2),
    updated_at: isoOffset(-1),
    customer: MOCK_CUSTOMERS[0],
    truck: MOCK_TRUCKS[0],
  },
  {
    id: 'book-002',
    quote_id: 'quote-006',
    customer_id: 'cust-006',
    truck_id: 'truck-002',
    scheduled_date: dateOffset(0),
    time_slot: 'morning',
    status: 'en_route',
    address: '3400 NW 36th St, Miami, FL 33142',
    waste_types: ['roofing_shingles'],
    load_size: 'full_truck',
    estimated_price: 550,
    completion_photos: [],
    created_at: isoOffset(-5),
    updated_at: isoOffset(0),
    customer: MOCK_CUSTOMERS[5],
    truck: MOCK_TRUCKS[1],
  },
  {
    id: 'book-003',
    quote_id: 'quote-008',
    customer_id: 'cust-008',
    truck_id: 'truck-001',
    scheduled_date: dateOffset(0),
    time_slot: 'afternoon',
    status: 'scheduled',
    address: '5500 NW 72nd Ave, Miami, FL 33166',
    waste_types: ['concrete_brick', 'metal_rebar', 'mixed_debris'],
    load_size: 'full_truck',
    estimated_price: 520,
    special_instructions: 'Ask for Fernando at front office',
    completion_photos: [],
    created_at: isoOffset(-6),
    updated_at: isoOffset(-1),
    customer: MOCK_CUSTOMERS[7],
    truck: MOCK_TRUCKS[0],
  },
  {
    id: 'book-004',
    quote_id: 'quote-016',
    customer_id: 'cust-008',
    truck_id: 'truck-002',
    scheduled_date: dateOffset(0),
    time_slot: 'afternoon',
    status: 'scheduled',
    address: '2800 NW 74th Ave, Miami, FL 33122',
    waste_types: ['concrete_brick', 'tile_ceramic'],
    load_size: 'full_truck',
    estimated_price: 520,
    completion_photos: [],
    created_at: isoOffset(-4),
    updated_at: isoOffset(-1),
    customer: MOCK_CUSTOMERS[7],
    truck: MOCK_TRUCKS[1],
  },
  {
    id: 'book-005',
    quote_id: 'quote-001',
    customer_id: 'cust-001',
    truck_id: 'truck-001',
    scheduled_date: dateOffset(-1),
    time_slot: 'morning',
    status: 'completed',
    address: '1420 NW 7th Ave, Miami, FL 33136',
    waste_types: ['concrete_brick', 'metal_rebar'],
    load_size: 'heavy',
    estimated_price: 425,
    final_price: 425,
    actual_weight: 1.8,
    completion_photos: [],
    created_at: isoOffset(-5),
    updated_at: isoOffset(-1),
    customer: MOCK_CUSTOMERS[0],
    truck: MOCK_TRUCKS[0],
  },
  {
    id: 'book-006',
    quote_id: 'quote-006',
    customer_id: 'cust-006',
    truck_id: 'truck-002',
    scheduled_date: dateOffset(-1),
    time_slot: 'afternoon',
    status: 'completed',
    address: '3400 NW 36th St, Miami, FL 33142',
    waste_types: ['roofing_shingles'],
    load_size: 'full_truck',
    estimated_price: 550,
    final_price: 550,
    actual_weight: 1.9,
    completion_photos: [],
    created_at: isoOffset(-6),
    updated_at: isoOffset(-1),
    customer: MOCK_CUSTOMERS[5],
    truck: MOCK_TRUCKS[1],
  },
  {
    id: 'book-007',
    quote_id: 'quote-008',
    customer_id: 'cust-008',
    truck_id: 'truck-001',
    scheduled_date: dateOffset(1),
    time_slot: 'morning',
    status: 'confirmed',
    address: '5500 NW 72nd Ave, Miami, FL 33166',
    waste_types: ['concrete_brick', 'mixed_debris'],
    load_size: 'full_truck',
    estimated_price: 520,
    completion_photos: [],
    created_at: isoOffset(-3),
    updated_at: isoOffset(0),
    customer: MOCK_CUSTOMERS[7],
    truck: MOCK_TRUCKS[0],
  },
  {
    id: 'book-008',
    quote_id: 'quote-001',
    customer_id: 'cust-001',
    truck_id: 'truck-002',
    scheduled_date: dateOffset(1),
    time_slot: 'afternoon',
    status: 'scheduled',
    address: '1420 NW 7th Ave, Miami, FL 33136',
    waste_types: ['concrete_brick'],
    load_size: 'medium',
    estimated_price: 300,
    completion_photos: [],
    created_at: isoOffset(-2),
    updated_at: isoOffset(0),
    customer: MOCK_CUSTOMERS[0],
    truck: MOCK_TRUCKS[1],
  },
  {
    id: 'book-009',
    quote_id: 'quote-016',
    customer_id: 'cust-008',
    truck_id: 'truck-001',
    scheduled_date: dateOffset(2),
    time_slot: 'morning',
    status: 'scheduled',
    address: '2800 NW 74th Ave, Miami, FL 33122',
    waste_types: ['concrete_brick', 'tile_ceramic'],
    load_size: 'heavy',
    estimated_price: 425,
    completion_photos: [],
    created_at: isoOffset(-1),
    updated_at: isoOffset(0),
    customer: MOCK_CUSTOMERS[7],
    truck: MOCK_TRUCKS[0],
  },
  {
    id: 'book-010',
    quote_id: 'quote-006',
    customer_id: 'cust-006',
    truck_id: 'truck-002',
    scheduled_date: dateOffset(2),
    time_slot: 'morning',
    status: 'confirmed',
    address: '3400 NW 36th St, Miami, FL 33142',
    waste_types: ['roofing_shingles'],
    load_size: 'full_truck',
    estimated_price: 550,
    completion_photos: [],
    created_at: isoOffset(-1),
    updated_at: isoOffset(0),
    customer: MOCK_CUSTOMERS[5],
    truck: MOCK_TRUCKS[1],
  },
  {
    id: 'book-011',
    quote_id: 'quote-001',
    customer_id: 'cust-001',
    truck_id: 'truck-001',
    scheduled_date: dateOffset(3),
    time_slot: 'morning',
    status: 'scheduled',
    address: '1420 NW 7th Ave, Miami, FL 33136',
    waste_types: ['metal_rebar'],
    load_size: 'medium',
    estimated_price: 300,
    completion_photos: [],
    created_at: isoOffset(0),
    updated_at: isoOffset(0),
    customer: MOCK_CUSTOMERS[0],
    truck: MOCK_TRUCKS[0],
  },
  {
    id: 'book-012',
    quote_id: 'quote-008',
    customer_id: 'cust-008',
    truck_id: 'truck-002',
    scheduled_date: dateOffset(3),
    time_slot: 'afternoon',
    status: 'scheduled',
    address: '5500 NW 72nd Ave, Miami, FL 33166',
    waste_types: ['mixed_debris'],
    load_size: 'heavy',
    estimated_price: 425,
    completion_photos: [],
    created_at: isoOffset(0),
    updated_at: isoOffset(0),
    customer: MOCK_CUSTOMERS[7],
    truck: MOCK_TRUCKS[1],
  },
];

// ============================================
// Dashboard Stats
// ============================================

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  todayRevenue: 1965,
  weekRevenue: 6450,
  monthRevenue: 24800,
  todayBookings: 4,
  pendingQuotes: 5,
  overdueInvoices: 1,
  truckUtilization: 85,
};

// ============================================
// Expenses
// ============================================

export const MOCK_EXPENSES: Expense[] = [
  { id: 'exp-001', date: dateOffset(-1), category: 'fuel', amount: 145.50, truck_id: 'truck-001', description: 'Diesel fill-up — Flash 1', created_at: isoOffset(-1) },
  { id: 'exp-002', date: dateOffset(-1), category: 'tipping_fees', amount: 170.00, truck_id: 'truck-001', description: 'Coastal Waste & Recycling (317 NE 71st St) — 2 tons mixed debris @ $85/ton', created_at: isoOffset(-1) },
  { id: 'exp-003', date: dateOffset(-2), category: 'fuel', amount: 132.00, truck_id: 'truck-002', description: 'Diesel fill-up — Flash 2', created_at: isoOffset(-2) },
  { id: 'exp-004', date: dateOffset(-3), category: 'tipping_fees', amount: 0, truck_id: 'truck-002', description: 'Asis Concrete Landfill (9201 NW 74th St) — clean concrete, FREE', created_at: isoOffset(-3) },
  { id: 'exp-005', date: dateOffset(-4), category: 'maintenance', amount: 450.00, truck_id: 'truck-001', description: 'Brake pad replacement — Flash 1 (2014 Isuzu NPR)', created_at: isoOffset(-4) },
  { id: 'exp-006', date: dateOffset(-5), category: 'labor', amount: 1200.00, description: 'Weekly driver wages (partial)', created_at: isoOffset(-5) },
  { id: 'exp-007', date: dateOffset(-6), category: 'fuel', amount: 155.00, truck_id: 'truck-001', description: 'Diesel fill-up — Flash 1', created_at: isoOffset(-6) },
  { id: 'exp-008', date: dateOffset(-7), category: 'insurance', amount: 850.00, description: 'Monthly commercial auto insurance', created_at: isoOffset(-7) },
  { id: 'exp-009', date: dateOffset(-7), category: 'tipping_fees', amount: 255.00, truck_id: 'truck-001', description: 'Coastal Waste & Recycling — 3 tons roofing @ $85/ton', created_at: isoOffset(-7) },
  { id: 'exp-010', date: dateOffset(-8), category: 'other', amount: 125.00, description: 'New tarps and tie-down straps', created_at: isoOffset(-8) },
];

// ============================================
// Lowercase aliases for API routes
// ============================================

// ============================================
// Historical Bookings (30 days back)
// ============================================

const historicalAddresses = [
  '1420 NW 7th Ave, Miami, FL 33136',
  '3400 NW 36th St, Miami, FL 33142',
  '5500 NW 72nd Ave, Miami, FL 33166',
  '2800 NW 74th Ave, Miami, FL 33122',
  '2200 Brickell Ave, Miami, FL 33129',
  '7700 N Kendall Dr, Miami, FL 33156',
  '6800 SW 40th St, Miami, FL 33155',
  '4100 NW 27th Ave, Miami, FL 33142',
  '9200 SW 72nd St, Miami, FL 33173',
  '8901 SW 142nd Ave, Miami, FL 33186',
];

const wasteOptions: (typeof MOCK_BOOKINGS[0]['waste_types'])[] = [
  ['concrete_brick', 'metal_rebar'], ['roofing_shingles'], ['mixed_debris'],
  ['drywall_plaster', 'wood_lumber'], ['concrete_brick', 'tile_ceramic'],
  ['wood_lumber'], ['mixed_debris', 'metal_rebar'], ['appliances_fixtures'],
];

const loadOptions: (typeof MOCK_BOOKINGS[0]['load_size'])[] = ['light', 'medium', 'heavy', 'full_truck'];
const priceMap = { light: 225, medium: 325, heavy: 450, full_truck: 550 };

for (let d = -30; d < -3; d++) {
  const jobsPerDay = d % 7 === 0 || d % 7 === 6 ? 1 : Math.floor(Math.random() * 3) + 2;
  for (let j = 0; j < jobsPerDay; j++) {
    const custIdx = (Math.abs(d) + j) % MOCK_CUSTOMERS.length;
    const truckIdx = j % 2;
    const wasteIdx = (Math.abs(d) + j) % wasteOptions.length;
    const loadIdx = (Math.abs(d) + j) % loadOptions.length;
    const load = loadOptions[loadIdx];
    const price = priceMap[load] + (Math.abs(d) % 5) * 25;
    const bookId = `book-hist-${Math.abs(d)}-${j}`;

    MOCK_BOOKINGS.push({
      id: bookId,
      quote_id: '',
      customer_id: MOCK_CUSTOMERS[custIdx].id,
      truck_id: MOCK_TRUCKS[truckIdx].id,
      scheduled_date: dateOffset(d),
      time_slot: j === 0 ? 'morning' : 'afternoon',
      status: 'completed',
      address: historicalAddresses[(Math.abs(d) + j) % historicalAddresses.length],
      waste_types: wasteOptions[wasteIdx],
      load_size: load,
      estimated_price: price,
      final_price: price,
      actual_weight: +(1.2 + Math.random() * 1.5).toFixed(1),
      completion_photos: [],
      created_at: isoOffset(d - 2),
      updated_at: isoOffset(d),
      customer: MOCK_CUSTOMERS[custIdx],
      truck: MOCK_TRUCKS[truckIdx],
    });
  }
}

// ============================================
// Invoices
// ============================================

function invoiceNum(n: number): string {
  return `INV-2026-${String(n).padStart(3, '0')}`;
}

const completedBookings = MOCK_BOOKINGS.filter((b) => b.status === 'completed');

export const MOCK_INVOICES: Invoice[] = completedBookings.slice(0, 20).map((b, i) => {
  const amount = b.final_price ?? b.estimated_price;
  const isPaid = i < 14;
  const isOverdue = !isPaid && i < 17;
  return {
    id: `inv-${String(i + 1).padStart(3, '0')}`,
    invoice_number: invoiceNum(i + 1),
    booking_id: b.id,
    customer_id: b.customer_id,
    amount,
    tax_amount: 0,
    total_amount: amount,
    status: isPaid ? 'paid' : isOverdue ? 'overdue' : 'sent',
    payment_method: isPaid ? (['zelle', 'check', 'cash', 'wire'] as const)[i % 4] : undefined,
    due_date: dateOffset(-30 + i * 2),
    paid_date: isPaid ? dateOffset(-28 + i * 2) : undefined,
    created_at: isoOffset(-30 + i),
    customer: MOCK_CUSTOMERS.find((c) => c.id === b.customer_id),
    booking: b,
  };
});

// ============================================
// Notifications
// ============================================

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  { id: 'notif-001', type: 'quote', title: 'New Quote Request', message: 'Ana Gutierrez submitted a new quote for tile removal', href: '/admin/quotes/quote-004', read: false, created_at: isoOffset(0) },
  { id: 'notif-002', type: 'quote', title: 'New Quote Request', message: 'David Lopez needs emergency mixed debris pickup', href: '/admin/quotes/quote-011', read: false, created_at: isoOffset(0) },
  { id: 'notif-003', type: 'quote', title: 'New Quote Request', message: 'Luis Perez submitted roofing + wood debris quote', href: '/admin/quotes/quote-014', read: false, created_at: isoOffset(0) },
  { id: 'notif-004', type: 'booking', title: 'Job Completed', message: 'Flash 1 completed job at 1420 NW 7th Ave', href: '/admin/bookings/book-005', read: true, created_at: isoOffset(-1) },
  { id: 'notif-005', type: 'booking', title: 'Job Completed', message: 'Flash 2 completed roofing pickup at NW 36th St', href: '/admin/bookings/book-006', read: true, created_at: isoOffset(-1) },
  { id: 'notif-006', type: 'invoice', title: 'Invoice Overdue', message: 'INV-2026-015 for James Mitchell is 5 days past due', href: '/admin/finances', read: false, created_at: isoOffset(-2) },
  { id: 'notif-007', type: 'payment', title: 'Payment Received', message: 'Carlos Hernandez paid $425 via Zelle', read: true, created_at: isoOffset(-1) },
  { id: 'notif-008', type: 'maintenance', title: 'Maintenance Due Soon', message: 'Flash 2 maintenance due in 5 days', href: '/admin/trucks', read: false, created_at: isoOffset(-1) },
];

// ============================================
// Maintenance Records
// ============================================

export const MOCK_MAINTENANCE: MaintenanceRecord[] = [
  { id: 'maint-001', truck_id: 'truck-001', date: dateOffset(-4), description: 'Brake pad replacement', cost: 450, mileage: 85200, created_at: isoOffset(-4) },
  { id: 'maint-002', truck_id: 'truck-002', date: dateOffset(-20), description: 'Oil change and filter', cost: 185, mileage: 141800, created_at: isoOffset(-20) },
  { id: 'maint-003', truck_id: 'truck-001', date: dateOffset(-45), description: 'Tire rotation and alignment', cost: 320, mileage: 84600, created_at: isoOffset(-45) },
  { id: 'maint-004', truck_id: 'truck-002', date: dateOffset(-60), description: 'Hydraulic lift service', cost: 780, mileage: 140200, created_at: isoOffset(-60) },
  { id: 'maint-005', truck_id: 'truck-001', date: dateOffset(-90), description: 'Oil change and filter', cost: 185, mileage: 83100, created_at: isoOffset(-90) },
];

// ============================================
// Fuel Logs
// ============================================

export const MOCK_FUEL_LOGS: FuelLog[] = [];
for (let w = 0; w < 8; w++) {
  MOCK_FUEL_LOGS.push(
    { id: `fuel-${w * 2 + 1}`, truck_id: 'truck-001', date: dateOffset(-w * 4), gallons: 42 + (w % 3) * 5, cost: 145 + (w % 3) * 15, mileage: 85200 - w * 320, created_at: isoOffset(-w * 4) },
    { id: `fuel-${w * 2 + 2}`, truck_id: 'truck-002', date: dateOffset(-w * 4 - 1), gallons: 38 + (w % 3) * 4, cost: 132 + (w % 3) * 12, mileage: 142100 - w * 280, created_at: isoOffset(-w * 4 - 1) },
  );
}

// ============================================
// Lowercase aliases for API routes
// ============================================

export const mockCustomers = MOCK_CUSTOMERS;
export const mockQuotes = MOCK_QUOTES;
export const mockBookings = MOCK_BOOKINGS;
export const mockTrucks = MOCK_TRUCKS;
export const mockExpenses = MOCK_EXPENSES;
export const mockDashboardStats = MOCK_DASHBOARD_STATS;
export const mockInvoices = MOCK_INVOICES;
export const mockNotifications = MOCK_NOTIFICATIONS;
